//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCPIAcquisition.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCPIAcquisition.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Current.
        /// </summary>
        internal static string ACCurrent {
            get {
                return ResourceManager.GetString("ACCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Voltage.
        /// </summary>
        internal static string ACVoltage {
            get {
                return ResourceManager.GetString("ACVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep.
        /// </summary>
        internal static string Beep {
            get {
                return ResourceManager.GetString("Beep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacitance.
        /// </summary>
        internal static string Capacitance {
            get {
                return ResourceManager.GetString("Capacitance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        internal static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Current.
        /// </summary>
        internal static string DCCurrent {
            get {
                return ResourceManager.GetString("DCCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Voltage.
        /// </summary>
        internal static string DCVoltage {
            get {
                return ResourceManager.GetString("DCVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits.
        /// </summary>
        internal static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Panel Display.
        /// </summary>
        internal static string FrontPanelDisplay {
            get {
                return ResourceManager.GetString("FrontPanelDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Measured Value.
        /// </summary>
        internal static string LatestMeasuredValue {
            get {
                return ResourceManager.GetString("LatestMeasuredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Function.
        /// </summary>
        internal static string MeasurementFunction {
            get {
                return ResourceManager.GetString("MeasurementFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance.
        /// </summary>
        internal static string Resistance {
            get {
                return ResourceManager.GetString("Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string Unit_Capacitance {
            get {
                return ResourceManager.GetString("Unit_Capacitance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Unit_Current {
            get {
                return ResourceManager.GetString("Unit_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hz.
        /// </summary>
        internal static string Unit_Frequency {
            get {
                return ResourceManager.GetString("Unit_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ω.
        /// </summary>
        internal static string Unit_Resistance {
            get {
                return ResourceManager.GetString("Unit_Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Unit_Time {
            get {
                return ResourceManager.GetString("Unit_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string Unit_Voltage {
            get {
                return ResourceManager.GetString("Unit_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
