name: Build app
on: push
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7'
      - name: Copy Ogg
        run: cp -r ogg flac\
      - name: Configure FLAC
        run: cd flac; cmake -G "Visual Studio 17 2022" -A x64 -DINSTALL_MANPAGES=OFF
      - name: Build FLAC
        run: cd flac; cmake --build . --config Release
      - name: Build
        run: MSBuild PlayPcmWin\PlayPcmWin\PlayPcmWin.sln -t:restore,build
      - name: Prepare Release
        run: cd PlayPcmWin\PlayPcmWin\bin\;
             mv v143\x64\Release\*.dll Release\net7.0-windows\;
             rm Release\net7.0-windows\*.pdb;
             mv Release\net7.0-windows\ Release\PlayPcmWin;
             Compress-Archive -Path Release\PlayPcmWin -DestinationPath ..\..\..\PlayPcmWin.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PlayPcmWin.zip
          path: PlayPcmWin.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: PlayPcmWin.zip
