name: Build app
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7'
      - name: Copy Ogg
        run: cp -r ogg flac\
      - name: Configure FLAC
        run: cd flac; cmake -G "Visual Studio 17 2022" -A x64 -DINSTALL_MANPAGES=OFF
      - name: Build FLAC
        run: cmake --build . --config Release
      - name: Build
        run: cd ..\; MSBuild PlayPcmWin\PlayPcmWin\PlayPcmWin.sln -t:restore,build
